import { NgModule } from '@angular/core';
import { MatButtonModule, 
         MatIconModule,
         MatFormFieldModule, 
         MatInputModule, 
         MatDatepickerModule,
         MatNativeDateModule, 
         MatCheckboxModule, 
         MatSidenavModule, 
         MatToolbarModule, 
         MatRadioModule,
         MatListModule,
         MatSelectModule,
         MatCardModule,
         MatTabsModule,
         MatProgressSpinnerModule,
         MatTableModule,
         MatSortModule,
         MatPaginatorModule,
         MatDialogModule,
         MatExpansionModule,
         MatStepperModule,
         MatSlideToggleModule,
         MatBadgeModule,
         MatMenuModule} from '@angular/material';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

@NgModule ({
imports: [MatButtonModule, 
    MatIconModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatDatepickerModule, 
    MatNativeDateModule, 
    MatCheckboxModule, 
    MatSidenavModule,
    MatToolbarModule,
    MatRadioModule,
    MatListModule,
    MatSelectModule,
    MatCardModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatDialogModule,
    MatExpansionModule,
    MatStepperModule,
    ReactiveFormsModule,
    MatSlideToggleModule,
    MatBadgeModule,
    MatMenuModule,
    HttpClientModule
],
exports: [MatButtonModule, 
    MatIconModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatDatepickerModule, 
    MatNativeDateModule, 
    MatCheckboxModule, 
    MatSidenavModule,
    MatToolbarModule,
    MatRadioModule,
    MatListModule,
    MatSelectModule,
    MatCardModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatDialogModule,
    MatExpansionModule,
    MatStepperModule,
    ReactiveFormsModule,
    MatSlideToggleModule,
    MatBadgeModule,
    MatMenuModule,
    HttpClientModule
]
})
export class MaterialModule {}